development:
  adapter: postgresql
  encoding: unicode
  database: thuviendientu_dev
  pool: 5
  username: postgres
  password:	postgres

test:
  adapter: postgresql
  encoding: unicode
  database: thuviendientu_test
  pool: 5
  username: postgres
  password:	postgres